### ISSUE TITLE
1382725

### ISSUE THREAD

**Issue by SpEcHiDe** [TelegramPlayGround/pyrogram#106]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

1382725

### Steps to reproduce

1382725

**Comment by KSKOP69** [comment]
```
[31-Oct-24 13:30:59 - ERROR] - asyncio - Task exception was never retrieved
future: <Task finished name='Task-950897' coro=<Client.handle_updates() done, defined at /usr/local/lib/python3.12/dist-packages/pyrogram/client.py:611> exception=RpcCallFail('Telegram says: [500 RPC_CALL_FAIL] (caused by "updates.GetChannelDifference") Pyrogram 2.1.33.13 thinks: Telegram is having internal problems. Please try again later')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/client.py", line 654, in handle_updates
    diff = await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 443, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 443, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 443, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 436, in invoke
    raise e from None
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 413, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 383, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/errors/rpc_error.py", line 107, in raise_it
    raise getattr(
pyrogram.errors.exceptions.internal_server_error_500.RpcCallFail: Telegram says: [500 RPC_CALL_FAIL] (caused by "updates.GetChannelDifference") Pyrogram 2.1.33.13 thinks: Telegram is having internal problems. Please try again later
[31-Oct-24 13:31:37 - ERROR] - asyncio - Task exception was never retrieved
future: <Task finished name='Task-951882' coro=<Client.handle_updates() done, defined at /usr/local/lib/python3.12/dist-packages/pyrogram/client.py:611> exception=RpcCallFail('Telegram says: [500 RPC_CALL_FAIL] (caused by "updates.GetChannelDifference") Pyrogram 2.1.33.13 thinks: Telegram is having internal problems. Please try again later')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/client.py", line 654, in handle_updates
    diff = await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 443, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 443, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 443, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 436, in invoke
    raise e from None
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 413, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 383, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/errors/rpc_error.py", line 107, in raise_it
    raise getattr(
pyrogram.errors.exceptions.internal_server_error_500.RpcCallFail: Telegram says: [500 RPC_CALL_FAIL] (caused by "updates.GetChannelDifference") Pyrogram 2.1.33.13 thinks: Telegram is having internal problems. Please try again later
[31-Oct-24 13:32:42 - ERROR] - asyncio - Task exception was never retrieved
future: <Task finished name='Task-953722' coro=<Client.handle_updates() done, defined at /usr/local/lib/python3.12/dist-packages/pyrogram/client.py:611> exception=RpcCallFail('Telegram says: [500 RPC_CALL_FAIL] (caused by "updates.GetChannelDifference") Pyrogram 2.1.33.13 thinks: Telegram is having internal problems. Please try again later')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/client.py", line 654, in handle_updates
    diff = await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 443, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 443, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 443, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 436, in invoke
    raise e from None
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 413, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 383, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/errors/rpc_error.py", line 107, in raise_it
    raise getattr(
pyrogram.errors.exceptions.internal_server_error_500.RpcCallFail: Telegram says: [500 RPC_CALL_FAIL] (caused by "updates.GetChannelDifference") Pyrogram 2.1.33.13 thinks: Telegram is having internal problems. Please try again later

```

Justed transfered from kurigram to pyrotgfork and got this error.
