### ISSUE TITLE
promote_chat_member PEER_FLOOD

### ISSUE THREAD

**Issue by fivepe** [TelegramPlayGround/pyrogram#112]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

client already set sleep_threshold, show PEER_FLOOD.

```
Traceback (most recent call last):
  File "aaa.py", line 44, in <module>
    member = app.promote_chat_member(channel_id, user_app, privileges=ChatPrivileges(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/chats/promote_chat_member.py", line 81, in promote_chat_member
    r = await self.invoke(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 413, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 383, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/errors/rpc_error.py", line 107, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.PeerFlood: Telegram says: [400 PEER_FLOOD] (caused by "channels.EditAdmin") Pyrogram 2.1.33.11 thinks: The method can't be used because your account is currently limited
```

### Steps to reproduce

```
app = Client("xxx", api_id=xxx, api_hash="xxx", phone_number="xxx", sleep_threshold=86400)

for user_app in user_apps:
        member = app.promote_chat_member(channel_id, user_app)
```

**Comment by SpEcHiDe** [comment]
It has nothing to do with `sleep_threshold` parameter.

**The method can't be used because your account is currently limited**
