### ISSUE TITLE
the handler is closed

### ISSUE THREAD

**Issue by fivepe** [TelegramPlayground/pyrogram#27]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

i am getting this exact error when sending files. it looks like this though,
this is really interrupting my bot. would appreciate any advice.

### Steps to reproduce

Traceback (most recent call last):
  File "/<redacted>/venv/lib/python3.12/site-packages/pyrogram/methods/advanced/save_file.py", line 109, in worker
    await session.invoke(data)
  File "/<redacted>/venv/lib/python3.12/site-packages/pyrogram/session/session.py", line 422, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<redacted>/venv/lib/python3.12/site-packages/pyrogram/session/session.py", line 422, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<redacted>/venv/lib/python3.12/site-packages/pyrogram/session/session.py", line 422, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 7 more times]
  File "/<redacted>/venv/lib/python3.12/site-packages/pyrogram/session/session.py", line 412, in invoke
    raise e from None
  File "/<redacted>/venv/lib/python3.12/site-packages/pyrogram/session/session.py", line 399, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<redacted>/venv/lib/python3.12/site-packages/pyrogram/session/session.py", line 350, in send
    raise e
  File "/<redacted>/venv/lib/python3.12/site-packages/pyrogram/session/session.py", line 347, in send
    await self.connection.send(payload)
  File "/<redacted>/venv/lib/python3.12/site-packages/pyrogram/connection/connection.py", line 69, in send
    await self.protocol.send(data)
  File "/<redacted>/venv/lib/python3.12/site-packages/pyrogram/connection/transport/tcp/tcp_abridged.py", line 38, in send
    await super().send(
  File "/<redacted>/venv/lib/python3.12/site-packages/pyrogram/connection/transport/tcp/tcp.py", line 104, in send
    raise OSError(e)
OSError: unable to perform operation on <TCPTransport closed=True reading=False 0x105e929b0>; the handler is closed
[10] Retrying "upload.SaveBigFilePart" due to: unable to perform operation on <TCPTransport closed=True reading=False 0x105e929b0>; the handler is closed
[10] Retrying "upload.SaveBigFilePart" due to: unable to perform operation on <TCPTransport closed=True reading=False 0x105e929b0>; the handler is closed
[10] Retrying "upload.SaveBigFilePart" due to: unable to perform operation on <TCPTransport closed=True reading=False 0x105e929b0>; the handler is closed
[10] Retrying "upload.SaveBigFilePart" due to: unable to perform operation on <TCPTransport closed=True reading=False 0x105e929b0>; the handler is closed
unable to perform operation on <TCPTransport closed=True reading=False 0x105e929b0>; the handler is closed

**Comment by SpEcHiDe** [comment]
I am also facing same issue, but I do not know how to solve it.

**Comment by annihilatorrrr** [comment]
> I am also facing same issue, but I do not know how to solve it.

same and A LOT LOT.

**Comment by annihilatorrrr** [comment]
> > I am also facing same issue, but I do not know how to solve it.
> 
> same and A LOT LOT.

i do restart only as only solution, happens too much for userbots than bots.

**Comment by fivepe** [comment]
my current solution is also to restart the client, but this will affect other ongoing tasks

> > > I am also facing same issue, but I do not know how to solve it.
> > 
> > 
> > same and A LOT LOT.
> 
> i do restart only as only solution, happens too much for userbots than bots.

my current solution is also to restart the client, but this will affect other ongoing tasks

**Comment by annihilatorrrr** [comment]
> my current solution is also to restart the client, but this will affect other ongoing tasks
> 
> > > > I am also facing same issue, but I do not know how to solve it.
> > > 
> > > 
> > > same and A LOT LOT.
> > 
> > 
> > i do restart only as only solution, happens too much for userbots than bots.
> 
> my current solution is also to restart the client, but this will affect other ongoing tasks

true, same.

**Comment by fivepe** [comment]
> Please retry with `pyrotgfork==2.1.32.9` and reply here if issue still persists.

still persists
![image](https://github.com/TelegramPlayGround/pyrogram/assets/131561603/b6b9808e-be9e-4af1-89cc-cbf4fa90f778)

**Comment by SpEcHiDe** [comment]
Please try again with 
```sh
pip uninstall -y pyrogram && pip install https://github.com/TelegramPlayGround/pyrogram/archive/unfixe-error-d.zip
```
