### ISSUE TITLE
cannot schedule new futures after shutdown

### ISSUE THREAD

**Issue by fivepe** [TelegramPlayGround/pyrogram#45]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

The following new error appears in the runtime log

### Steps to reproduce

Task exception was never retrieved
future: <Task finished name='Task-34612131' coro=<Session.restart() done, defined at /usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py:201> exception=RuntimeError('cannot schedule new futures after shutdown')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 213, in restart
    await self.start()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 168, in start
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 138, in start
    api_id=await self.client.storage.api_id(),
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/storage/sqlite_storage.py", line 301, in api_id
    return await self._accessor(value)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/storage/sqlite_storage.py", line 287, in _accessor
    return await self._get() if value == object else await self._set(value)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/storage/sqlite_storage.py", line 271, in _get
    return await self.loop.run_in_executor(self.executor, self._get_impl, attr)
  File "uvloop/loop.pyx", line 2729, in uvloop.loop.Loop.run_in_executor
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 179, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown

**Comment by SpEcHiDe** [comment]
Please try again with 
```sh
pip uninstall -y pyrogram && pip install https://github.com/TelegramPlayGround/pyrogram/archive/unfixe-error-d.zip
```
