### ISSUE TITLE
Handler is closed

### ISSUE THREAD

**Issue by anasty17** [TelegramPlayGround/pyrogram#79]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

2024-08-22 17:15:39,521 - pyrogram.connection.transport.tcp.tcp - ERROR - Send exception: RuntimeError unable to perform operation on <TCPTransport closed=True reading=False 0x2219c8c0>; the handler is closed

### Steps to reproduce

i have never saw this in official lib
I notice this in all new mods
I can't reproduce this happens when bot idle

### Logs

```shell
2024-08-22 17:15:39,521 - pyrogram.connection.transport.tcp.tcp - ERROR - Send exception: RuntimeError unable to perform operation on <TCPTransport closed=True reading=False 0x2219c8c0>; the handler is closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/connection/transport/tcp/tcp.py", line 145, in send
    self.writer.write(data)
  File "/usr/lib/python3.12/asyncio/streams.py", line 346, in write
    self._transport.write(data)
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x2219c8c0>; the handler is closed
2024-08-23 09:36:44,687 - pyrogram.connection.transport.tcp.tcp - ERROR - Send exception: RuntimeError unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/connection/transport/tcp/tcp.py", line 145, in send
    self.writer.write(data)
  File "/usr/lib/python3.12/asyncio/streams.py", line 346, in write
    self._transport.write(data)
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
2024-08-23 09:36:44,731 - pyrogram.connection.transport.tcp.tcp - ERROR - Send exception: RuntimeError unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/connection/transport/tcp/tcp.py", line 145, in send
    self.writer.write(data)
  File "/usr/lib/python3.12/asyncio/streams.py", line 346, in write
    self._transport.write(data)
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
2024-08-23 09:36:44,732 - pyrogram.connection.transport.tcp.tcp - ERROR - Send exception: RuntimeError unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/connection/transport/tcp/tcp.py", line 145, in send
    self.writer.write(data)
  File "/usr/lib/python3.12/asyncio/streams.py", line 346, in write
    self._transport.write(data)
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
2024-08-23 09:36:44,733 - pyrogram.connection.transport.tcp.tcp - ERROR - Send exception: RuntimeError unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/connection/transport/tcp/tcp.py", line 145, in send
    self.writer.write(data)
  File "/usr/lib/python3.12/asyncio/streams.py", line 346, in write
    self._transport.write(data)
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
2024-08-23 09:36:44,767 - pyrogram.connection.transport.tcp.tcp - ERROR - Send exception: RuntimeError unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/connection/transport/tcp/tcp.py", line 145, in send
    self.writer.write(data)
  File "/usr/lib/python3.12/asyncio/streams.py", line 346, in write
    self._transport.write(data)
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
2024-08-23 09:36:44,768 - pyrogram.connection.transport.tcp.tcp - ERROR - Send exception: RuntimeError unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/connection/transport/tcp/tcp.py", line 145, in send
    self.writer.write(data)
  File "/usr/lib/python3.12/asyncio/streams.py", line 346, in write
    self._transport.write(data)
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
2024-08-23 09:36:44,768 - pyrogram.connection.transport.tcp.tcp - ERROR - Send exception: RuntimeError unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/connection/transport/tcp/tcp.py", line 145, in send
    self.writer.write(data)
  File "/usr/lib/python3.12/asyncio/streams.py", line 346, in write
    self._transport.write(data)
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
2024-08-23 09:36:44,768 - pyrogram.connection.transport.tcp.tcp - ERROR - Send exception: RuntimeError unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/connection/transport/tcp/tcp.py", line 145, in send
    self.writer.write(data)
  File "/usr/lib/python3.12/asyncio/streams.py", line 346, in write
    self._transport.write(data)
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
2024-08-23 09:36:44,769 - pyrogram.connection.transport.tcp.tcp - ERROR - Send exception: RuntimeError unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/connection/transport/tcp/tcp.py", line 145, in send
    self.writer.write(data)
  File "/usr/lib/python3.12/asyncio/streams.py", line 346, in write
    self._transport.write(data)
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
2024-08-23 09:36:44,769 - pyrogram.connection.transport.tcp.tcp - ERROR - Send exception: RuntimeError unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/connection/transport/tcp/tcp.py", line 145, in send
    self.writer.write(data)
  File "/usr/lib/python3.12/asyncio/streams.py", line 346, in write
    self._transport.write(data)
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0xe2cf5c045cc0>; the handler is closed
```

**Comment by fivepe** [comment]
updated to latest version, this error still occurs
```
Send exception: RuntimeError unable to perform operation on <TCPTransport closed=True reading=False 0x8dd6630>; the handler is closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/connection/transport/tcp/tcp.py", line 145, in send
    self.writer.write(data)
  File "/usr/lib/python3.8/asyncio/streams.py", line 341, in write
    self._transport.write(data)
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x8dd6630>; the handler is closed
```

**Comment by SpEcHiDe** [comment]
**I do not get this error in any of my bots**.

**Comment by fivepe** [comment]
As long as I run it for a while, there will be a lot of errors like this. It may also be related to the number of robot users, and the amount of concurrency is relatively high.
![image](https://github.com/user-attachments/assets/6e7959e9-fc80-4308-b4bd-0d10e6f9ad41)

Running multiple clients in one program can easily trigger this error when uploading or downloading at the same time. Personally, I feel that this problem will occur if there are too many concurrent clients.
