### ISSUE TITLE
Persistent timestamp invalid

### ISSUE THREAD

**Issue by anasty17** [TelegramPlayGround/pyrogram#86]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-630' coro=<Client.handle_updates() done, defined at /usr/local/lib/python3.12/dist-packages/pyrogram/client.py:613> exception=PersistentTimestampInvalid('Telegram says: [400 PERSISTENT_TIMESTAMP_INVALID] (caused by "updates.GetChannelDifference") Pyrogram 2.1.33.4 thinks: Persistent timestamp invalid.')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/client.py", line 656, in handle_updates
    diff = await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 518, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 478, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/errors/rpc_error.py", line 107, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.PersistentTimestampInvalid: Telegram says: [400 PERSISTENT_TIMESTAMP_INVALID] (caused by "updates.GetChannelDifference") Pyrogram 2.1.33.4 thinks: Persistent timestamp invalid.

### Steps to reproduce

I only started the bot then i did nothing. After 15 min since starting first time error raised then same error raised twice again after 30 min. This also never happened before using the official lib

### Logs

```shell
2024-08-31 19:31:05,345 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-630' coro=<Client.handle_updates() done, defined at /usr/local/lib/python3.12/dist-packages/pyrogram/client.py:613> exception=PersistentTimestampInvalid('Telegram says: [400 PERSISTENT_TIMESTAMP_INVALID] (caused by "updates.GetChannelDifference") Pyrogram 2.1.33.4 thinks: Persistent timestamp invalid.')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/client.py", line 656, in handle_updates
    diff = await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 518, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 478, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/errors/rpc_error.py", line 107, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.PersistentTimestampInvalid: Telegram says: [400 PERSISTENT_TIMESTAMP_INVALID] (caused by "updates.GetChannelDifference") Pyrogram 2.1.33.4 thinks: Persistent timestamp invalid.
2024-08-31 19:58:07,339 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1540' coro=<Client.handle_updates() done, defined at /usr/local/lib/python3.12/dist-packages/pyrogram/client.py:613> exception=PersistentTimestampInvalid('Telegram says: [400 PERSISTENT_TIMESTAMP_INVALID] (caused by "updates.GetChannelDifference") Pyrogram 2.1.33.4 thinks: Persistent timestamp invalid.')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/client.py", line 656, in handle_updates
    diff = await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 518, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 478, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/errors/rpc_error.py", line 107, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.PersistentTimestampInvalid: Telegram says: [400 PERSISTENT_TIMESTAMP_INVALID] (caused by "updates.GetChannelDifference") Pyrogram 2.1.33.4 thinks: Persistent timestamp invalid.
2024-08-31 19:58:47,173 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1574' coro=<Client.handle_updates() done, defined at /usr/local/lib/python3.12/dist-packages/pyrogram/client.py:613> exception=PersistentTimestampInvalid('Telegram says: [400 PERSISTENT_TIMESTAMP_INVALID] (caused by "updates.GetChannelDifference") Pyrogram 2.1.33.4 thinks: Persistent timestamp invalid.')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/client.py", line 656, in handle_updates
    diff = await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 518, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/session/session.py", line 478, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.12/dist-packages/pyrogram/errors/rpc_error.py", line 107, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.PersistentTimestampInvalid: Telegram says: [400 PERSISTENT_TIMESTAMP_INVALID] (caused by "updates.GetChannelDifference") Pyrogram 2.1.33.4 thinks: Persistent timestamp invalid.
```

**Comment by SpEcHiDe** [comment]
**I do not get this error in any of my bots**.
